<?php
        // put your code here
        echo 'ELmafrood View';
        echo '<br>';
        echo '<br>';
        include_once 'View\ClientView.php';
        $ClientView = new ClientView();
        $ClientView->selectUserType();
        echo '<br>';
        $ClientView->Checkvaildation();
        echo '<br>';
        $ClientView->Login();
        echo '<br>';
        $ClientView->Signup();
        echo '<br>';
        $ClientView->SetUserData();
        echo '<br>';
        echo '<br>';
        include_once 'View\DonorView.php';
        $DonorView = new DonorView();
        $DonorView->addDonation();
        echo '<br>';
        $DonorView->cancelDonation();
        echo '<br>';
        
        $clientID=1;
        include_once 'View\EmployeeView.php';
        $EmployeeView = new EmployeeView();
        echo '<br>';
        $EmployeeView->Checkvaildation();
        echo '<br>';
        $EmployeeView->Login();
        echo '<br>';
        $EmployeeView->SetUserData();
        echo '<br>';
        $EmployeeView->Signup();
        echo '<br>';
        $EmployeeView->addClient();
        echo '<br>';
        $EmployeeView->deleteClient($clientID);
        echo '<br>';
        $EmployeeView->getPatientsData();
        echo '<br>';
        $EmployeeView->selectClientType();
        echo '<br>';
        $EmployeeView->selectUserType();
        echo '<br>';
        $EmployeeView->setPatientsData();
        echo '<br>';
        $EmployeeView->updateClientInfo($clientID);
        echo '<br>';
        echo '<br>';
        include_once 'View\EventsView.php';
        $EventView = new EventsView();
        $EventView->ViewAllEvents();
        echo '<br>';
        echo '<br>';
        
        $EmpID=1;
        include_once 'View\ManagerView.php';
        $ManagerView = new ManagerView();
        $ManagerView->Checkvaildation();
        echo '<br>';
        $ManagerView->Login();
        echo '<br>';
        $ManagerView->SetUserData();
        echo '<br>';
        $ManagerView->UpdateEmployee($EmpID);
        echo '<br>';
        $ManagerView->addEmployee();
        echo '<br>';
        $ManagerView->notifyEmployee($EmpID);
        echo '<br>';
        $ManagerView->removeEmployee($EmpID);
        echo '<br>';
        $ManagerView->selectUserType();
        echo '<br>';
        echo '<br>';
        
        $eventID=1;
        include_once 'View\OrgnizerObserver.php';
        $OrgnizerObserver = new OrgnizerObserver();
        $OrgnizerObserver->Notify();
        echo '<br>';
        $OrgnizerObserver->updateEvents($eventID);
        echo '<br>';
        echo '<br>';
        
        include_once 'View\OrgnizerView.php';
        $OrgnizerView = new OrgnizerView();
        $OrgnizerView->Checkvaildation();
        echo '<br>';
        $OrgnizerView->Login();
        echo '<br>';
        $OrgnizerView->Notify();
        echo '<br>';
        $OrgnizerView->SetUserData();
        echo '<br>';
        $OrgnizerView->addEvents();
        echo '<br>';
        $OrgnizerView->deleteEvents($eventID);
        echo '<br>';
        $OrgnizerView->selectUserType();
        echo '<br>';
        echo '<br>';
        include_once 'View\TypeofDonaationView.php';
        $TypeofDonaationView= new TypeofDonaationView();
        $TypeofDonaationView->donatethroughATM();
        echo '<br>';
        $TypeofDonaationView->donatethroughRepresentaive();
        echo '<br>';
        $TypeofDonaationView->donatethroughSMS();
            echo '<br>';
            echo '<br>';
            include_once 'View\VolunteerView.php';
        $VolunteerView= new VolunteerView();
        $VolunteerView->requestProgram();
        echo '<br>';
        echo '<br>';
?>;